version: '3.3'
services:
  redis:
    container_name: "redis_prod"
    image: redis
    ports:
      - '6379:6379'
    networks:
      - async_api_net

  elasticsearch:
    container_name: "elasticsearch_prod"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - '9200:9200'
    environment:
      - "discovery.type=single-node"
    networks:
      - async_api_net

  service:
    container_name: "service_prod"
    build: ./service
    env_file:
      - .env
    ports:
      - '8000:8000'
#    environment:
#      - REDIS_HOST=redis
#      - ELASTIC_HOST=elasticsearch
    depends_on:
      - redis
      - elasticsearch
    networks:
      - async_api_net

networks:
  async_api_net:
    name: async_api_net