version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5435:5432'
    env_file:
      - ./.env

  redis:
    container_name: "redis"
    image: redis
    ports:
      - '6379:6379'

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - '9200:9200'

  service:
    build: .
    volumes:
      - static_value:/code/static/
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d
      - static_value:/var/html/static/
    depends_on:
      - service
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_value: